model_name: "ChocolateCake"
enc_dim: 2048
gpu: 0

components:
  ScienceNerd:
    gpu: 0
    base_model: "EleutherAI/gpt-neo-2.7B"
    precision: "half"
    redpajama_subsets:
      - "common_crawl"
      - "c4"
      - "github"
    batch_size: 1
    learning_rate: 0.000006
    num_batches: 64000
    optimizer: "adam"

  Books3:
    gpu: 1
    base_model: "EleutherAI/gpt-neo-2.7B"
    precision: "half"
    redpajama_subsets:
      - "book"
      - "arxiv"
    batch_size: 1
    learning_rate: 0.000005
    num_batches: 32000
    optimizer: "adam"

  Books:
    gpu: 0
    base_model: "EleutherAI/gpt-neo-2.7B"
    precision: "half"
    redpajama_subsets:
      - "wikipedia"
      - "stackexchange"
    batch_size: 1
    learning_rate: 0.000005
    num_batches: 64000
    optimizer: "adam"
